version: '3.3'
services:
  ivy:
    build: .
    ports:
     - "80:8080"
  keycloak:
    image: "quay.io/keycloak/keycloak:9.0.3"
    ports:
     - "8080:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
